# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a200tsbg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Users/Benoit Brizard/Documents/1-hiv19/ELE3311/lab/tp3/tp3_bb_4avril/tp3_bb_1avril/tp3_bb_1avril/tp3_bb_30mars/TP3_BB_ARD.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Benoit Brizard/Documents/1-hiv19/ELE3311/lab/tp3/tp3_bb_4avril/tp3_bb_1avril/tp3_bb_1avril/tp3_bb_30mars/TP3_BB_ARD.xpr} [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {c:/Users/Benoit Brizard/Documents/1-hiv19/ELE3311/lab/tp3/tp3_bb_4avril/tp3_bb_1avril/tp3_bb_1avril/tp3_bb_30mars/TP3_BB_ARD.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/Benoit Brizard/Documents/1-hiv19/ELE3311/lab/tp3/tp3_bb_4avril/tp3_bb_1avril/tp3_bb_1avril/tp3_bb_30mars/rtl/ROM_data.vhd}
  {C:/Users/Benoit Brizard/Documents/1-hiv19/ELE3311/lab/tp3/tp3_bb_4avril/tp3_bb_1avril/tp3_bb_1avril/tp3_bb_30mars/rtl/antirebond_1b.vhd}
  {C:/Users/Benoit Brizard/Documents/1-hiv19/ELE3311/lab/tp3/tp3_bb_4avril/tp3_bb_1avril/tp3_bb_1avril/tp3_bb_30mars/rtl/antirebond_1b_dfm.vhd}
  {C:/Users/Benoit Brizard/Documents/1-hiv19/ELE3311/lab/tp3/tp3_bb_4avril/tp3_bb_1avril/tp3_bb_1avril/tp3_bb_30mars/rtl/cmd_addr.vhd}
  {C:/Users/Benoit Brizard/Documents/1-hiv19/ELE3311/lab/tp3/tp3_bb_4avril/tp3_bb_1avril/tp3_bb_1avril/tp3_bb_30mars/rtl/compteur_25dutycycle.vhd}
  {C:/Users/Benoit Brizard/Documents/1-hiv19/ELE3311/lab/tp3/tp3_bb_4avril/tp3_bb_1avril/tp3_bb_1avril/tp3_bb_30mars/rtl/compteur_bcd_2.vhd}
  {C:/Users/Benoit Brizard/Documents/1-hiv19/ELE3311/lab/tp3/tp3_bb_4avril/tp3_bb_1avril/tp3_bb_1avril/tp3_bb_30mars/rtl/delay_cnt.vhd}
  {C:/Users/Benoit Brizard/Documents/1-hiv19/ELE3311/lab/tp3/tp3_bb_4avril/tp3_bb_1avril/tp3_bb_1avril/tp3_bb_30mars/rtl/display_fsm.vhd}
  {C:/Users/Benoit Brizard/Documents/1-hiv19/ELE3311/lab/tp3/tp3_bb_4avril/tp3_bb_1avril/tp3_bb_1avril/tp3_bb_30mars/rtl/diviseur_horloge.vhd}
  {C:/Users/Benoit Brizard/Documents/1-hiv19/ELE3311/lab/tp3/tp3_bb_4avril/tp3_bb_1avril/tp3_bb_1avril/tp3_bb_30mars/rtl/horloge.vhd}
  {C:/Users/Benoit Brizard/Documents/1-hiv19/ELE3311/lab/tp3/tp3_bb_4avril/tp3_bb_1avril/tp3_bb_1avril/tp3_bb_30mars/rtl/msa_horloge.vhd}
  {C:/Users/Benoit Brizard/Documents/1-hiv19/ELE3311/lab/tp3/tp3_bb_4avril/tp3_bb_1avril/tp3_bb_1avril/tp3_bb_30mars/rtl/power_reg.vhd}
  {C:/Users/Benoit Brizard/Documents/1-hiv19/ELE3311/lab/tp3/tp3_bb_4avril/tp3_bb_1avril/tp3_bb_1avril/tp3_bb_30mars/rtl/spi_master.vhd}
  {C:/Users/Benoit Brizard/Documents/1-hiv19/ELE3311/lab/tp3/tp3_bb_4avril/tp3_bb_1avril/tp3_bb_1avril/tp3_bb_30mars/rtl/sync_io_1.vhd}
  {C:/Users/Benoit Brizard/Documents/1-hiv19/ELE3311/lab/tp3/tp3_bb_4avril/tp3_bb_1avril/tp3_bb_1avril/tp3_bb_30mars/rtl/horloge_oled.vhd}
}
read_ip -quiet {{C:/Users/Benoit Brizard/Documents/1-hiv19/ELE3311/lab/tp3/tp3_bb_4avril/tp3_bb_1avril/tp3_bb_1avril/tp3_bb_30mars/TP3_BB_ARD.srcs/sources_1/ip/clk_wiz/clk_wiz.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/Benoit Brizard/Documents/1-hiv19/ELE3311/lab/tp3/tp3_bb_4avril/tp3_bb_1avril/tp3_bb_1avril/tp3_bb_30mars/TP3_BB_ARD.srcs/sources_1/ip/clk_wiz/clk_wiz_board.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Benoit Brizard/Documents/1-hiv19/ELE3311/lab/tp3/tp3_bb_4avril/tp3_bb_1avril/tp3_bb_1avril/tp3_bb_30mars/TP3_BB_ARD.srcs/sources_1/ip/clk_wiz/clk_wiz.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Benoit Brizard/Documents/1-hiv19/ELE3311/lab/tp3/tp3_bb_4avril/tp3_bb_1avril/tp3_bb_1avril/tp3_bb_30mars/TP3_BB_ARD.srcs/sources_1/ip/clk_wiz/clk_wiz_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Benoit Brizard/Documents/1-hiv19/ELE3311/lab/tp3/tp3_bb_4avril/tp3_bb_1avril/tp3_bb_1avril/tp3_bb_30mars/constraints/NexysVideo_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Benoit Brizard/Documents/1-hiv19/ELE3311/lab/tp3/tp3_bb_4avril/tp3_bb_1avril/tp3_bb_1avril/tp3_bb_30mars/constraints/NexysVideo_Master.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top horloge_oled -part xc7a200tsbg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef horloge_oled.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file horloge_oled_utilization_synth.rpt -pb horloge_oled_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
