webtalk_init -webtalk_dir D:/tp3_bb_27mars/TP3_BB_ARD/TP3_BB_ARD.sim/sim_1/synth/func/xsim/xsim.dir/horloge_oled_TB_func_synth/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Mar 28 09:51:46 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174141621_174141622_174419766_045" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "5ffa1e56-7d8b-428d-ae00-1ad17d0741ad" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2f9a300bca30476d9ca561ff29dd62b8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3392 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1001 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "8" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "16.15_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "13384_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3436813311 -regid "174141621_174141622_174419766_045" -xml D:/tp3_bb_27mars/TP3_BB_ARD/TP3_BB_ARD.sim/sim_1/synth/func/xsim/xsim.dir/horloge_oled_TB_func_synth/webtalk/usage_statistics_ext_xsim.xml -html D:/tp3_bb_27mars/TP3_BB_ARD/TP3_BB_ARD.sim/sim_1/synth/func/xsim/xsim.dir/horloge_oled_TB_func_synth/webtalk/usage_statistics_ext_xsim.html -wdm D:/tp3_bb_27mars/TP3_BB_ARD/TP3_BB_ARD.sim/sim_1/synth/func/xsim/xsim.dir/horloge_oled_TB_func_synth/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
